classes:
- system.linux.system.single
- system.linux.system.single.debian
- system.linux.network.dynamic_hosts
- system.salt.minion.single
- system.rsyslog.client.single
- cluster.mp-mcp.openstack
#- cluster.mp-mcp.infra.proxy
- cluster.mp-mcp.infra.secrets
parameters:
  _param:
    # Don't set it "false" before you configure sudo policies and enable power users.
    linux_system_user_sudo: true

    apt_mk_version: stable
    # TODO: Revert openstack repo part after refactoring here: https://mirantis.jira.com/browse/PROD-17500
    openstack_version: ocata
    jenkins_pipelines_branch: master
    salt_control_trusty_image: http://images.mirantis.com/ubuntu-14-04-x64-mcp${_param:apt_mk_version}.qcow2
    salt_control_xenial_image: http://images.mirantis.com/ubuntu-16-04-x64-mcp${_param:apt_mk_version}.qcow2
    infra_config_hostname: cfg01
    salt_minion_ca_host: ${_param:infra_config_hostname}.${_param:cluster_domain}
    # infra service addresses
    infra_config_address: 10.1.0.90
    infra_config_deploy_address: 172.17.52.106

    cluster_domain: mp-mcp-networking.local
    cluster_name: mp-mcp
    cluster_public_host: ${_param:openstack_proxy_address}
    control_network_netmask: 255.255.255.0
    tenant_network_netmask: 255.255.255.0

    dns_server01: 8.8.8.8
    dns_server02: 8.8.4.4
    control_vlan: 10
    tenant_vlan: 20

    deploy_network_netmask: 255.255.255.0
    deploy_network_gateway: 10.0.0.1

    # MaaS parameters
    infra_maas_node01_deploy_address: ${_param:infra_config_deploy_address}
    infra_maas_node01_hostname: ${_param:infra_config_hostname}
    infra_kvm_address: 10.0.1.240
    infra_kvm_node01_address: 10.0.1.241
    infra_kvm_node02_address: 10.0.1.242
    infra_kvm_node03_address: 10.0.1.243
    infra_kvm_node01_deploy_address: 10.0.0.241
    infra_kvm_node02_deploy_address: 10.0.0.242
    infra_kvm_node03_deploy_address: 10.0.0.243
    infra_kvm_node01_hostname: kvm01
    infra_kvm_node02_hostname: kvm02
    infra_kvm_node03_hostname: kvm03

#    glusterfs_node01_address: ${_param:infra_kvm_node01_address}
#    glusterfs_node02_address: ${_param:infra_kvm_node02_address}
#    glusterfs_node03_address: ${_param:infra_kvm_node03_address}
    linux_dhcp_interface:
      enabled: true
      type: eth
      proto: dhcp
    linux_single_interface:
      enabled: true
      type: eth
      proto: static
      address: ${_param:single_address}
      netmask: ${_param:control_network_netmask}
      name_servers:
        - ${_param:dns_server01}
        - ${_param:dns_server02}

  salt:
    minion:
      trusted_ca_minions:
        - ${_param:salt_minion_ca_host}

  linux:
    network:
      dhclient:
        enabled: true
        request:
          - subnet-mask
          - broadcast-address
          - time-offset
          - routers
          - domain-name
          - domain-name-servers
          - domain-search
          - host-name
          - dhcp6.name-servers
          - dhcp6.domain-search
          - dhcp6.fqdn
          - dhcp6.sntp-servers
          - netbios-name-servers
          - netbios-scope
          - interface-mtu
          - rfc3442-classless-static-routes
      host:
        hostname:
          address: ${_param:single_address}
          names:
          - ${linux:network:hostname}
          - ${linux:network:fqdn}
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
          - cfg
          - cfg.${_param:cluster_domain}
        kvm01:
          address: ${_param:infra_kvm_node01_address}
          names:
          - ${_param:infra_kvm_node01_hostname}
          - ${_param:infra_kvm_node01_hostname}.${_param:cluster_domain}
        kvm02:
          address: ${_param:infra_kvm_node02_address}
          names:
          - ${_param:infra_kvm_node02_hostname}
          - ${_param:infra_kvm_node02_hostname}.${_param:cluster_domain}
        kvm03:
          address: ${_param:infra_kvm_node03_address}
          names:
          - ${_param:infra_kvm_node03_hostname}
          - ${_param:infra_kvm_node03_hostname}.${_param:cluster_domain}
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
      service:
        apt-daily.timer:
          status: dead
