classes:
- system.backupninja.server.single
- system.xtrabackup.server.single
- system.glusterfs.client.cluster
- system.glusterfs.client.volume.backup
parameters:
  _param:
    backupninja_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDyDkz2R3V1PZUyyLYw1cT/TbKvB3tqe7CnkB4rij6QjoxeywnI7fNpjUyulrc2J667Q12QphBMGh4mNtoKEQyDVIrAmHcAF5IdTFgFP8oLjXNTzDdD19OaMF+auRjBVv1MshkxxXKhTJkPowkAc/jwOsfF5yS4gEIg7VYGEwXK7MRNB6zsRAKQVOXsLAiWxOjNbuq6b6K60yR1WyVBKkYJcsl0fnpV3EdHnslywqWcwd8V6ikat93j79aHqWLwwANpHLJHnyPuCxkIaMryAY6wbVjs6nSEWqLRenvLtRTWaNoQfWySvwk9KW07NyEBUL1rVafwR+VqGooBvYIhMVKp
    xtrabackup_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDyDkz2R3V1PZUyyLYw1cT/TbKvB3tqe7CnkB4rij6QjoxeywnI7fNpjUyulrc2J667Q12QphBMGh4mNtoKEQyDVIrAmHcAF5IdTFgFP8oLjXNTzDdD19OaMF+auRjBVv1MshkxxXKhTJkPowkAc/jwOsfF5yS4gEIg7VYGEwXK7MRNB6zsRAKQVOXsLAiWxOjNbuq6b6K60yR1WyVBKkYJcsl0fnpV3EdHnslywqWcwd8V6ikat93j79aHqWLwwANpHLJHnyPuCxkIaMryAY6wbVjs6nSEWqLRenvLtRTWaNoQfWySvwk9KW07NyEBUL1rVafwR+VqGooBvYIhMVKp
  backupninja:
    server:
      home_dir: /srv/volumes/backup/backupninja
  xtrabackup:
    server:
      backup_dir: /srv/volumes/backup/xtrabackup
